/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC4 (number 76), LCD_EN
  @{ */
#define BOARD_INITPINS_LCD_EN_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_EN_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_EN_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                         /* @} */

/*! @name PORTC12 (number 84), LCD_RS
  @{ */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RS_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                         /* @} */

/*! @name PORTC3 (number 73), LCD_D7
  @{ */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D7_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D7_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                         /* @} */

/*! @name PORTC2 (number 72), LCD_D6
  @{ */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D6_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                         /* @} */

/*! @name PORTA2 (number 36), LCD_D5
  @{ */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LCD_D5_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LCD_D5_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                         /* @} */

/*! @name PORTB23 (number 69), LCD_D4
  @{ */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D4_PIN 23U    /*!<@brief PORTB pin index: 23 */
                                         /* @} */

/*! @name PORTB2 (number 55), BUTTON_ALL_ADC
  @{ */
#define BOARD_INITPINS_BUTTON_ALL_ADC_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_ALL_ADC_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                                 /* @} */

/*! @name PORTB3 (number 56), BLUE_OUT
  @{ */
#define BOARD_INITPINS_BLUE_OUT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BLUE_OUT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BLUE_OUT_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                           /* @} */

/*! @name PORTB10 (number 58), BLUE_IN
  @{ */
#define BOARD_INITPINS_BLUE_IN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BLUE_IN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BLUE_IN_PIN 10U    /*!<@brief PORTB pin index: 10 */
                                          /* @} */

/*! @name PORTC11 (number 83), RED_OUT
  @{ */
#define BOARD_INITPINS_RED_OUT_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_RED_OUT_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_RED_OUT_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                          /* @} */

/*! @name PORTC10 (number 82), RED_IN
  @{ */
#define BOARD_INITPINS_RED_IN_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_RED_IN_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_RED_IN_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
