/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA25 (coord J12), LCD_D7
  @{ */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LCD_D7_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_LCD_D7_PIN 25U    /*!<@brief PORTA pin index: 25 */
                                         /* @} */

/*! @name PORTC2 (coord A12), LCD_D6
  @{ */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D6_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                         /* @} */

/*! @name PORTC5 (coord D8), LCD_D5
  @{ */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D5_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D5_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                         /* @} */

/*! @name PORTC12 (coord A7), LCD_D4
  @{ */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D4_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                         /* @} */

/*! @name PORTB18 (coord D12), LCD_RS
  @{ */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_RS_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_RS_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                         /* @} */

/*! @name PORTB19 (coord D11), LCD_EN
  @{ */
#define BOARD_INITPINS_LCD_EN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_EN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_EN_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                         /* @} */

/*! @name PORTB7 (coord F11), BUTTON_ALL_ADC
  @{ */
#define BOARD_INITPINS_BUTTON_ALL_ADC_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BUTTON_ALL_ADC_PIN 7U     /*!<@brief PORTB pin index: 7 */
                                                 /* @} */

/*! @name PORTB6 (coord F12), BLUE_OUT
  @{ */
#define BOARD_INITPINS_BLUE_OUT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BLUE_OUT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BLUE_OUT_PIN 6U     /*!<@brief PORTB pin index: 6 */
                                           /* @} */

/*! @name PORTB5 (coord G9), BLUE_IN
  @{ */
#define BOARD_INITPINS_BLUE_IN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BLUE_IN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BLUE_IN_PIN 5U     /*!<@brief PORTB pin index: 5 */
                                          /* @} */

/*! @name PORTB3 (coord G11), RED_OUT
  @{ */
#define BOARD_INITPINS_RED_OUT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RED_OUT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RED_OUT_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                          /* @} */

/*! @name PORTB2 (coord G12), RED_IN
  @{ */
#define BOARD_INITPINS_RED_IN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RED_IN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RED_IN_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
