/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC18 (coord D7), LCD_D7
  @{ */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D7_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D7_PIN 18U    /*!<@brief PORTC pin index: 18 */
                                         /* @} */

/*! @name PORTC6 (coord A10), LCD_D4
  @{ */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_D4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_D4_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                         /* @} */

/*! @name PORTC19 (coord C7), LCD_RS
  @{ */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RS_PIN 19U    /*!<@brief PORTC pin index: 19 */
                                         /* @} */

/*! @name PORTB19 (coord D11), LCD_EN
  @{ */
#define BOARD_INITPINS_LCD_EN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_EN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_EN_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                         /* @} */

/*! @name PORTB12 (coord E12), LCD_D5
  @{ */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D5_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D5_PIN 12U    /*!<@brief PORTB pin index: 12 */
                                         /* @} */

/*! @name PORTB13 (coord E11), LCD_D6
  @{ */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D6_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D6_PIN 13U    /*!<@brief PORTB pin index: 13 */
                                         /* @} */

/*! @name PORTA7 (coord L10), BUTTONS_ALL_ADC
  @{ */
#define BOARD_INITPINS_BUTTONS_ALL_ADC_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_BUTTONS_ALL_ADC_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                                  /* @} */

/*! @name PORTA8 (coord K9), BLUE_OUT
  @{ */
#define BOARD_INITPINS_BLUE_OUT_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_BLUE_OUT_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_BLUE_OUT_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                           /* @} */

/*! @name PORTD1 (coord A5), BLUE_IN
  @{ */
#define BOARD_INITPINS_BLUE_IN_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_BLUE_IN_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_BLUE_IN_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                          /* @} */

/*! @name PORTB2 (coord G11), RED_OUT
  @{ */
#define BOARD_INITPINS_RED_OUT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RED_OUT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RED_OUT_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                          /* @} */

/*! @name PORTB3 (coord G10), RED_IN
  @{ */
#define BOARD_INITPINS_RED_IN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RED_IN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RED_IN_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
