/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_adc16.h"
#include "fsl_pit.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for ADC0 peripheral */
#define BUTTON_ADC_PERIPHERAL ADC0
/* BUTTON_ADC interrupt vector ID (number). */
#define BUTTON_ADC_IRQN ADC0_IRQn
/* BUTTON_ADC interrupt handler identifier. */
#define BUTTON_ADC_IRQHANDLER ADC0_IRQHandler
/* BOARD_InitPeripherals defines for PIT0 */
/* Definition of peripheral ID. */
#define TIMEBASE_PERIPHERAL PIT0
/* Definition of clock source. */
#define TIMEBASE_CLOCK_SOURCE kCLOCK_BusClk
/* Definition of clock source frequency. */
#define TIMEBASE_CLK_FREQ CLOCK_GetFreq(TIMEBASE_CLOCK_SOURCE)
/* Definition of ticks count for channel 0. */
#define TIMEBASE_0_TICKS USEC_TO_COUNT(1000000U, TIMEBASE_CLK_FREQ) - 1U
/* Definition of ticks count for cahnnel 1. */
#define TIMEBASE_1_TICKS 86399U

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern adc16_channel_config_t BUTTON_ADC_channelsConfig[1];
extern const adc16_config_t BUTTON_ADC_config;
extern const adc16_channel_mux_mode_t BUTTON_ADC_muxMode;
extern const adc16_hardware_average_mode_t BUTTON_ADC_hardwareAverageMode;
extern const pit_config_t TIMEBASE_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
